package main

import (
	"fmt"
	// "log"
	// "os/exec"
	"regexp"
	"strings"
)

func main() {
	tnsString := `# tnsnames.ora Network Configuration File: D:\Program Files\instantclient_11_2\network\admin\tnsnames.ora
# Generated by Oracle configuration tools.

dzdz01 =
  (DESCRIPTION =
    (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = TCP)(HOST = 127.0.0.1)(PORT = 1521))
    )
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SID = dzdz01)
    )
  )

#DZDZ_V0_111 =
#  (DESCRIPTION =
#    (ADDRESS_LIST =
#      (ADDRESS = (PROTOCOL = TCP)(HOST = 172.30.11.230)(PORT = 1521))
#    )
#    (CONNECT_DATA =
#      (SERVER = DEDICATED)
#      (SID = jh1)
#    )
#  )
#
#DZDZ_V0_133 =
#  (DESCRIPTION =
#    (ADDRESS_LIST =
#      (ADDRESS = (PROTOCOL = TCP)(HOST = 172.30.11.231)(PORT = 1521))
#    )
#    (CONNECT_DATA =
#      (SERVER = DEDICATED)
#      (SID = jh2)
#    )
#  )
#
#DZDZ_V0_000 =
#  (DESCRIPTION =
#    (ADDRESS_LIST =
#      (ADDRESS = (PROTOCOL = TCP)(HOST = 172.30.11.232)(PORT = 1521))
#    )
#    (CONNECT_DATA =
#      (SERVER = DEDICATED)
#      (SID = jh3)
#    )
#  )

#####################################################

#XXXXXX = (DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=192.168.0.143)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=sjdz1)))

DZDZ_DEV_11200 =
  (DESCRIPTION =
    (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = TCP)(HOST = 172.30.11.230)(PORT = 1521))
    )
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SID = DZDZ)
    )
  )

DZDZ_DEV_13300 =
  (DESCRIPTION =
    (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = TCP)(HOST = 172.30.11.231)(PORT = 1521))
    )
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SID = DZDZ)
    )
  )

DZDZ_DEV_00000 =
  (DESCRIPTION =
    (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = TCP)(HOST = 172.30.11.232)(PORT = 1521))
    )
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SID = DZDZ000)
    )
  )


JH_DEV_000000 =
  (DESCRIPTION =
    (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = TCP)(HOST = 172.30.11.131)(PORT = 1521))
    )
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SID = v9djh1)
    )
  )

JH_TEST_000000 =
  (DESCRIPTION =
    (ADDRESS_LIST =
      (ADDRESS = (PROTOCOL = TCP)(HOST = 172.30.11.191)(PORT = 1521))
    )
    (CONNECT_DATA =
      (SERVER = DEDICATED)
      (SID = v9tjh1)
    )
  )`

	re, _ := regexp.Compile("(#*[\\w]*)([\\s]*=[\\s]*\\([\\s]*DESCRIPTION)")
	tnsentries := re.FindAllString(tnsString, -1)
	for i, tnsentrie := range tnsentries {
		rs := []rune(tnsentrie) //如果entry 以# 开头，则忽略
		if rs[0] != '#' {
			fmt.Println(i, strings.Split(tnsentrie, "=")[0])
		}
	}

}
